---

- name: set group_vars_dir
  set_fact: "group_vars_dir='group_vars{{ inventory_file | replace(inventory_dir, \"\") }}'"

- name: create conf.d files
  copy:
    src: "{{ item }}"
    dest: "{{ tinedockercompose_confd_path }}"
    owner: tine20
    group: root
    mode: 0640
  with_fileglob:
    - "{{ group_vars_dir }}/conf.d/*.php"
  become: true

- name: create conf.d files (j2)
  template:
    src: "{{ item }}"
    dest: "{{ tinedockercompose_confd_path }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: tine20
    group: root
    mode: 0640
  with_fileglob:
    - "{{ group_vars_dir }}/conf.d/*.j2"
  become: true

- name: deploy custom docker-compose.yml
  template:
    src: "{{ item }}"
    dest: "{{ tinedockercompose_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0640
  with_fileglob:
    - "{{ group_vars_dir }}/docker-compose.yml.j2"
  become: true
  when:
    - tinedockercompose_custom_compose is defined
    - tinedockercompose_custom_compose|bool == true

- name: create script files
  copy:
    src: "{{ item }}"
    dest: "{{ tinedockercompose_path }}/scripts"
    owner: root
    group: root
    mode: 0740
  with_fileglob:
    - "{{ group_vars_dir }}/scripts/*.sh"
  become: true
