#!/usr/bin/env bash

MYSQL_HOST=${MYSQL_HOST:-db}

mysql -h$MYSQL_HOST -uroot -p"$MYSQL_ROOT_PASSWORD" -e"CREATE DATABASE IF NOT EXISTS dovecot"
mysql -h$MYSQL_HOST -uroot -p"$MYSQL_ROOT_PASSWORD" -e"CREATE DATABASE IF NOT EXISTS postfix"

mysql -h$MYSQL_HOST -uroot -p"$MYSQL_ROOT_PASSWORD" -e"CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
mysql -h$MYSQL_HOST -uroot -p"$MYSQL_ROOT_PASSWORD" -e"GRANT ALL PRIVILEGES ON postfix.* TO '$MYSQL_USER'@'%'"
mysql -h$MYSQL_HOST -uroot -p"$MYSQL_ROOT_PASSWORD" -e"GRANT ALL PRIVILEGES ON dovecot.* TO '$MYSQL_USER'@'%'"

mysql -h$MYSQL_HOST -uroot -p"$MYSQL_ROOT_PASSWORD" "dovecot" < /config/dovecot_tables.sql
mysql -h$MYSQL_HOST -uroot -p"$MYSQL_ROOT_PASSWORD" "postfix" < /config/postfix_tables.sql

echo "mail stack db init"
