#!/usr/bin/env bash

php /usr/share/tine20/setup.php --install --config /etc/tine20/config.inc.php -- \
  adminLoginName="${TINE20_LOGIN_USERNAME:-tine20admin}" \
  adminPassword="${TINE20_LOGIN_PASSWORD:-tine20admin}" \
  adminEmailAddress="${TINE20_ADMIN_EMAIL:-tine20admin@example.org}" \
  acceptedTermsVersion=1000 \
  imap="${TINE20_EMAIL_IMAP}" \
  smtp="${TINE20_EMAIL_SMTP}" \
  sieve="${TINE20_EMAIL_SIEVE}" \
  authentication="${TINE20_AUTHENTICATION}" \
  accounts="${TINE20_ACCOUNTS}"