#!/usr/bin/env bash

TINE20_APPLICATION_TO_INSTALL=${TINE20_APPLICATION_TO_INSTALL:-'ActiveSync,Calendar,Felamimail,CoreData,Filemanager,Sales,Timetracker,Tasks,Crm,HumanResources,Inventory'}
TINE20_CONFIG_PATH=${TINE20_CONFIG_PATH:-'/etc/tine20/config.inc.php'}

cmd="php /usr/share/tine20/setup.php --install --config ${TINE20_CONFIG_PATH} ${TINE20_APPLICATION_TO_INSTALL} --"

if [ -n "${TINE20_LOGIN_USERNAME}" ]; then
  cmd="$cmd adminLoginName='${TINE20_LOGIN_USERNAME}'"
fi

if [ -n "${TINE20_LOGIN_PASSWORD}" ]; then
  cmd="$cmd adminPassword='${TINE20_LOGIN_PASSWORD}'"
fi

if [ -n "${TINE20_ADMIN_EMAIL}" ]; then
  cmd="$cmd adminEmailAddress='${TINE20_ADMIN_EMAIL}'"
fi

if [ -n "${TINE20_ACCEPTED_TERMS_VERSION}" ]; then
  cmd="$cmd acceptedTermsVersion='${TINE20_ACCEPTED_TERMS_VERSION}'"
fi

if [ -n "${TINE20_EMAIL_IMAP}" ]; then
  cmd="$cmd imap='${TINE20_EMAIL_IMAP}'"
fi

if [ -n "${TINE20_EMAIL_SMTP}" ]; then
  cmd="$cmd smtp='${TINE20_EMAIL_SMTP}'"
fi

if [ -n "${TINE20_EMAIL_SIEVE}" ]; then
  cmd="$cmd sieve='${TINE20_EMAIL_SIEVE}'"
fi

if [ -n "${TINE20_AUTHENTICATION}" ]; then
  cmd="$cmd authentication='${TINE20_AUTHENTICATION}'"
fi

if [ -n "${TINE20_ACCOUNTS}" ]; then
  cmd="$cmd accounts='${TINE20_ACCOUNTS}'"
fi

if [ -n "${TINE20_LICENSE_PATH}" ]; then
  if [ -f "${TINE20_LICENSE_PATH}" ]; then
    cmd="$cmd license='${TINE20_LICENSE_PATH}'"  
  else 
    echo "TINE20_LICENSE_PATH is not a file, ommiting it."
  fi
fi

if [ -n "${TINE20_INSTALL_LANG}" ]; then
  cmd="$cmd lang='${TINE20_INSTALL_LANG}'"
fi

echo $cmd

su tine20 -c "$cmd"