<?php
// Call Setup_Backend_Schema_TableTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Setup_Backend_Schema_TableTest::main');
}

require_once 'PHPUnit/Framework.php';

//require_once '\xampp\htdocs\tine20\Setup\Backend\Schema\Table.php';

/**
 * Test class for Setup_Backend_Schema_Table.
 * Generated by PHPUnit on 2008-04-23 at 17:26:04.
 */
class Setup_Backend_Schema_TableTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Setup_Backend_Schema_Table
     * @access protected
     */
    protected $object;

    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('TableTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
	
		$table = array(
					'XmlString' =>
							'<table>
					            <name>test_table</name>
					            <version>1</version>
					            <declaration>
					                <field>
					                    <name>id</name>
					                    <type>integer</type>
					                    <autoincrement>true</autoincrement>
					                </field>
					                <field>
					                    <name>name</name>
					                    <type>text</type>
					                    <length>128</length>
					                    <notnull>true</notnull>
					                </field>
					                <index>
					                    <name>id</name>
					                    <primary>true</primary>
					                    <field>
					                        <name>id</name>
					                    </field>
					                </index>
					            </declaration>
					        </table>'
					);
						
        $this->object = new Setup_Backend_Schema_Table($table);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

	
	
    /**
     * @todo Implement testAddDeclarationField().
     */
    public function testAddDeclarationField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

	public function test_setTableFromXml(){
	
	
	}
	
	public function test_setTableFromArray(){
	
	
	}
	
	public function test_setTableFromObject(){
	
	
	}
	
    /**
     * @todo Implement testSetDeclarationField().
     */
    public function testSetDeclarationField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddDeclarationIndex().
     */
    public function testAddDeclarationIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetDeclarationIndex().
     */
    public function testSetDeclarationIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddIndex().
     */
    public function testAddIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetIndex().
     */
    public function testSetIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetForeign().
     */
    public function testSetForeign() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFixFieldKey().
     */
    public function testFixFieldKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}

// Call Setup_Backend_Schema_TableTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Setup_Backend_Schema_TableTest::main') {
    Setup_Backend_Schema_TableTest::main();
}
?>
