#!/bin/sh
NAME=$1

FROM_IMAGE="${REGISTRY}/${NAME}-commit:${CI_PIPELINE_ID}-${PHP_VERSION}"
DESTINATION_IMAGE="${REGISTRY}/${NAME}:$(echo $CI_COMMIT_REF_NAME | sed sI/I-Ig)-${PHP_VERSION}"

docker pull "${FROM_IMAGE}"
docker tag "${FROM_IMAGE}" "${DESTINATION_IMAGE}"
docker push "${DESTINATION_IMAGE}"
