<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title><?php echo $this->title ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=8; IE=7" />
</head>
 <body>
    <img alt="<?php echo Tinebase_Config::getInstance()->get(Tinebase_Config::BRANDING_TITLE) ?>"
         style="max-width:400px;max-height:80px;" src="<?php echo $this->logoPath ?>">
    <h1><?php echo $this->pwtext ?></h1>
    <form method="post" action="">
        <input type="password" name="dlpassword"/>
        <input type="submit" value="<?php echo $this->submittext ?>">
    </form>
</body>
</html>
