<?php
/**
 * Tine 2.0
 *
 * @package     Voipmanager
 * @license     http://www.gnu.org/licenses/agpl.html AGPL3
 * @copyright   Copyright (c) 2008 Metaways Infosystems GmbH (http://www.metaways.de)
 * @author      Lars Kneschke <l.kneschke@metaways.de>
 * @version     $Id: Release0.php 3134 2008-07-02 17:04:25Z twadewitz $
 */

class Voipmanager_Setup_Update_Release0 extends Setup_Update_Abstract
{
    /**
     * rebuild snom_settings
     */    
    public function update_1()
    {
        $tableDefinition = "
          <table>
            <name>snom_settings</name>
            <engine>InnoDB</engine>
            <charset>utf8</charset>
            <version>1</version>
            <declaration>
                <field>
                    <name>id</name>
                    <type>text</type>
                    <length>40</length>
                    <notnull>true</notnull>
                </field>
                <field>
                    <name>name</name>
                    <type>text</type>
                    <length>150</length>
                    <notnull>true</notnull>
                </field>
                <field>
                    <name>description</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>true</notnull>
                </field> 
                <field>
                    <name>web_language</name>
                    <type>enum</type>
                    <value>English</value>
                    <value>Deutsch</value>
                    <value>Espanol</value>
                    <value>Francais</value>
                    <value>Italiano</value>
                    <value>Nederlands</value>
                    <value>Portugues</value>
                    <value>Suomi</value>
                    <value>Svenska</value>
                    <value>Dansk</value>
                    <value>Norsk</value>
                    <default>English</default>
                </field>
                <field>
                    <name>language</name>
                    <type>enum</type>
                    <value>English</value>
                    <value>English(UK)</value>
                    <value>Deutsch</value>
                    <value>Espanol</value>
                    <value>Francais</value>
                    <value>Italiano</value>
                    <value>Cestina</value>
                    <value>Nederlands</value>
                    <value>Polski</value>
                    <value>Portugues</value>
                    <value>Slovencina</value>
                    <value>Suomi</value>
                    <value>Svenska</value>
                    <value>Dansk</value>
                    <value>Norsk</value>
                    <value>Japanese</value>
                    <value>Chinese</value>
                    <default>English</default>
                </field>
                <field>
                    <name>display_method</name>
                    <type>enum</type>
                    <value>full_contact</value>
                    <value>display_name</value>
                    <value>display_number</value>
                    <value>display_name_number</value>
                    <value>display_number_name</value>
                    <default>display_name</default>
                </field>
                <field>
                    <name>mwi_notification</name>
                    <type>enum</type>
                    <value>silent</value>
                    <value>beep</value>
                    <value>reminder</value>
                    <default>silent</default>
                </field>
                <field>
                    <name>mwi_dialtone</name>
                    <type>enum</type>
                    <value>normal</value>
                    <value>stutter</value>
                    <default>stutter</default>
                </field>
                <field>
                    <name>headset_device</name>
                    <type>enum</type>
                    <value>none</value>
                    <value>headset_rj</value>
                    <default>none</default>
                </field>
                <field>
                    <name>with_flash</name>
                    <type>enum</type>
                    <value>true</value>
                    <value>false</value>
                    <notnull>false</notnull>
                </field>
                <field>
                    <name>message_led_other</name>
                    <type>enum</type>
                    <value>on</value>
                    <value>off</value>
                    <default>on</default>
                </field>
                <field>
                    <name>global_missed_counter</name>
                    <type>enum</type>
                    <value>on</value>
                    <value>off</value>
                    <default>on</default>
                </field>
                <field>
                    <name>scroll_outgoing</name>
                    <type>enum</type>
                    <value>on</value>
                    <value>off</value>
                    <default>on</default>
                </field>
                <field>
                    <name>show_local_line</name>
                    <type>enum</type>
                    <value>on</value>
                    <value>off</value>
                    <default>off</default>
                </field>
                <field>
                    <name>show_call_status</name>
                    <type>enum</type>
                    <value>on</value>
                    <value>off</value>
                    <default>off</default>
                </field>
                <field>
                    <name>redirect_event</name>
                    <type>enum</type>
                    <value>none</value>
                    <value>all</value>
                    <value>busy</value>
                    <value>time</value>            
                    <default>none</default>
                </field>
                <field>
                    <name>redirect_number</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>
                </field>
                <field>
                    <name>redirect_always_on_code</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>
                </field>
                <field>
                    <name>redirect_always_off_code</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>
                </field>
                <field>
                    <name>redirect_busy_number</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>
                </field>
                <field>
                    <name>redirect_busy_on_code</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>
                </field>
                <field>
                    <name>redirect_busy_off_code</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>
                </field>
                <field>
                    <name>redirect_time</name>
                    <type>integer</type>
                    <length>255</length>
                    <notnull>false</notnull>    
                </field>                
                <field>
                    <name>redirect_time_number</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>
                </field>
                <field>
                    <name>redirect_time_on_code</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>
                </field>
                <field>
                    <name>redirect_time_off_code</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>
                </field>
                <field>
                    <name>dnd_on_code</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>
                </field>
                <field>
                    <name>dnd_off_code</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>
                </field>
                <field>
                    <name>ringer_headset_device</name>
                    <type>enum</type>
                    <value>speaker</value>
                    <value>headset</value>
                    <default>speaker</default>
                </field>
                <field>
                    <name>ring_sound</name>
                    <type>enum</type>
                    <value>Ringer1</value>
                    <value>Ringer2</value>
                    <value>Ringer3</value>
                    <value>Ringer4</value>
                    <value>Ringer5</value>
                    <value>Ringer6</value>
                    <value>Ringer7</value>
                    <value>Ringer8</value>
                    <value>Ringer9</value>
                    <value>Ringer10</value>
                    <value>Silent</value>
                    <default>Ringer1</default>
                </field>
                <field>
                    <name>alert_internal_ring_text</name>
                    <type>text</type>
                    <length>255</length>
                    <default>alert-internal</default>
                </field>
                <field>
                    <name>alert_internal_ring_sound</name>
                    <type>enum</type>
                    <value>Ringer1</value>
                    <value>Ringer2</value>
                    <value>Ringer3</value>
                    <value>Ringer4</value>
                    <value>Ringer5</value>
                    <value>Ringer6</value>
                    <value>Ringer7</value>
                    <value>Ringer8</value>
                    <value>Ringer9</value>
                    <value>Ringer10</value>
                    <value>Silent</value>
                    <default>Ringer1</default>
                </field>                    
                <field>
                    <name>alert_external_ring_text</name>
                    <type>text</type>
                    <length>255</length>
                    <default>alert-external</default>
                </field>
                <field>
                    <name>alert_external_ring_sound</name>
                    <type>enum</type>
                    <value>Ringer1</value>
                    <value>Ringer2</value>
                    <value>Ringer3</value>
                    <value>Ringer4</value>
                    <value>Ringer5</value>
                    <value>Ringer6</value>
                    <value>Ringer7</value>
                    <value>Ringer8</value>
                    <value>Ringer9</value>
                    <value>Ringer10</value>
                    <value>Silent</value>
                    <default>Ringer1</default>
                </field>                    
                <field>
                    <name>alert_group_ring_text</name>                    
                    <type>text</type>
                    <length>255</length>
                    <default>alert-group</default>                    
                </field>
                <field>
                    <name>alert_group_ring_sound</name>
                    <type>enum</type>
                    <value>Ringer1</value>
                    <value>Ringer2</value>
                    <value>Ringer3</value>
                    <value>Ringer4</value>
                    <value>Ringer5</value>
                    <value>Ringer6</value>
                    <value>Ringer7</value>
                    <value>Ringer8</value>
                    <value>Ringer9</value>
                    <value>Ringer10</value>
                    <value>Silent</value>
                    <default>Ringer1</default>
                </field>
                <field>                    
                    <name>friends_ring_sound</name>
                    <type>enum</type>
                    <value>Ringer1</value>
                    <value>Ringer2</value>
                    <value>Ringer3</value>
                    <value>Ringer4</value>
                    <value>Ringer5</value>
                    <value>Ringer6</value>
                    <value>Ringer7</value>
                    <value>Ringer8</value>
                    <value>Ringer9</value>
                    <value>Ringer10</value>
                    <value>Silent</value>
                    <default>Ringer1</default>
                </field>
                <field>                    
                    <name>family_ring_sound</name>
                    <type>enum</type>
                    <value>Ringer1</value>
                    <value>Ringer2</value>
                    <value>Ringer3</value>
                    <value>Ringer4</value>
                    <value>Ringer5</value>
                    <value>Ringer6</value>
                    <value>Ringer7</value>
                    <value>Ringer8</value>
                    <value>Ringer9</value>
                    <value>Ringer10</value>
                    <value>Silent</value>
                    <default>Ringer1</default>
                </field>
                <field>                    
                    <name>colleagues_ring_sound</name>
                    <type>enum</type>
                    <value>Ringer1</value>
                    <value>Ringer2</value>
                    <value>Ringer3</value>
                    <value>Ringer4</value>
                    <value>Ringer5</value>
                    <value>Ringer6</value>
                    <value>Ringer7</value>
                    <value>Ringer8</value>
                    <value>Ringer9</value>
                    <value>Ringer10</value>
                    <value>Silent</value>
                    <default>Ringer1</default>
                </field>
                <field>                    
                    <name>vip_ring_sound</name>
                    <type>enum</type>
                    <value>Ringer1</value>
                    <value>Ringer2</value>
                    <value>Ringer3</value>
                    <value>Ringer4</value>
                    <value>Ringer5</value>
                    <value>Ringer6</value>
                    <value>Ringer7</value>
                    <value>Ringer8</value>
                    <value>Ringer9</value>
                    <value>Ringer10</value>
                    <value>Silent</value>
                    <default>Ringer1</default>
                </field>
                <field>
                    <name>custom_melody_url</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>
                </field>                    
                <field>
                    <name>auto_connect_indication</name>
                    <type>enum</type>
                    <value>on</value>
                    <value>off</value>
                </field>                   
                <field>
                    <name>auto_connect_type</name>
                    <type>enum</type>
                    <value>auto_connect_type_handsfree</value>
                    <value>auto_connect_type_handset</value>
                    <value>auto_connect_type_headset</value>
                    <default>auto_connect_type_handsfree</default>
                </field>
                <field>
                    <name>privacy_out</name>
                    <type>enum</type>
                    <value>on</value>
                    <value>off</value>
                    <default>off</default>
                </field>             
                <field>
                    <name>privacy_in</name>
                    <type>enum</type>
                    <value>on</value>
                    <value>off</value>
                    <default>off</default>
                </field>             
                <field>
                    <name>presence_timeout</name>
                    <type>integer</type>
                    <length>20</length>
                    <default>15</default>
                </field>
                <field>
                    <name>enable_keyboard_lock</name>
                    <type>enum</type>
                    <value>on</value>
                    <value>off</value>
                    <default>on</default>
                </field>            
                <field>
                    <name>keyboard_lock</name>
                    <type>enum</type>
                    <value>on</value>
                    <value>off</value>
                    <default>off</default>
                </field>     
                <field>
                    <name>keyboard_lock_pw</name>       
                    <type>integer</type>
                    <length>50</length>
                    <default>15</default>
                </field>     
                <field>
                    <name>keyboard_lock_emergency</name>
                    <type>text</type>
                    <length>255</length>
                    <default>911 112 110 999</default>                                                       
                </field>
                <field>
                    <name>emergency_proxy</name>
                    <type>text</type>
                    <length>255</length>
                    <notnull>false</notnull>                                                       
                </field>  
                <field>
                    <name>call_waiting</name>
                    <type>enum</type>
                    <value>on</value>
                    <value>visual</value>
                    <value>ringer</value>
                    <value>off</value>
                    <default>off</default>
                </field>     
                <field>
                    <name>web_language_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>language_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>display_method_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>tone_scheme_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>mwi_notification_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>mwi_dialtone_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>headset_device_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>message_led_other_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>global_missed_counter_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>scroll_outgoing_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>show_local_line_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>show_call_status_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>redirect_event_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>redirect_number_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>     
                <field>
                    <name>redirect_time_writable</name>
                    <type>boolean</type>
                    <default>false</default>
                </field>   
                <index>
                    <name>id</name>
                    <primary>true</primary>
                    <field>
                        <name>id</name>
                    </field>
                </index>
            </declaration>
        </table>";

        $table = Setup_Backend_Schema_Table_Factory::factory('String', $tableDefinition); 

        $this->_backend->dropTable('snom_settings');
        $this->_backend->createTable($table);        
        $this->setApplicationVersion('Voipmanager', '1.1');
    }  
          
}