Ext.ns('Tine.Tinebase');

const HTOTOPSecretField = Ext.extend(Ext.form.FieldSet, {
    /**
     * @cfg {String} type h|totp
     */
    type: 'totp',
    
    initComponent: function() {
        this.title = i18n._('Secret Key');
        this.explainText = new Ext.form.Label({
            text: i18n._("Please note: After saving you can not view this autogenerated secret key again!")
        });
        this.secretField = new Ext.form.TextField({
            //@TODO clipboard plugin!
            name: 'secret',
            anchor: '100%',
            hideLabel: true,
            setValue: this.setValue.createDelegate(this)
            // getValue: this.getValue.createDelegate(this)
        });
        this.qrField = new Ext.BoxComponent({
            width: 150,
            height: 150,
            html: '<img style="width: 100%; height: 100%"/>'
        });
        this.items = [
            this.explainText,
            this.secretField,
            this.qrField
        ];

        this.supr().initComponent.call(this);
    },
    
    onRender: function() {
        this.supr().onRender.apply(this, arguments);
        this.editDialog = this.findParentBy(function (c) {
            return c instanceof Tine.widgets.dialog.EditDialog
        });
    },
    setValue: function(value, record) {
        const supr = Ext.form.TextField.prototype.setValue.createDelegate(this.secretField);
        
        if (!value && !record.id) {
            supr(i18n._('Generating secret key ...'));
            this.secretField.setDisabled(true);
            import(/* webpackChunkName: "Tinebase/js/base32-encode" */ 'base32-encode').then((module) => {
                const bytes = new Uint8Array(35);
                window.crypto.getRandomValues(bytes);
                supr(module.default(bytes, 'RFC3548'));
                this.secretField.setDisabled(false);
                this.onValueChange();
            });
        } else {
            this.explainText.setText(i18n._("Existing secret keys can't be viewed. You need to generate a new one if the old got lost."));
            this.secretField.hide();
            this.qrField.hide();
        }
        
        // this.afterIsRendered().then(() => {
        //     this.editDialog.window.setTitle('yes');
        // });
        
    },

    onValueChange: async function() {
        const secret = this.secretField.getValue();
        const type = this.type.toLowerCase();
        const account = encodeURIComponent(JSON.parse(this.editDialog.record.json.account_id).accountLoginName);
        const issuer = encodeURIComponent(window.location.hostname);

        let uri = `otpauth://${type}/${issuer}:${account}?secret=${secret}&issuer=${issuer}`;
        // uri += "&algorithm=" + this.editDialog.record.get('algorithm');
        // uri += "&digits=" + this.editDialog.record.get('digits');
        // uri += "&period=" + this.editDialog.record.get('period');
        if (type == "hotp")
            uri += "&counter=" + (this.editDialog.record.get('counter') || 0);
        // uri += "&lock=" + ???; // freeOTP only?
        uri += "&image=" + encodeURIComponent(Tine.Tinebase.common.getUrl() + Tine.Tinebase.registry.get('installLogo')); // freeOTP only?;
        
        const QRCode = await import(/* webpackChunkName: "Tinebase/js/qrcode" */ 'qrcode');
        const imgURL = await QRCode.toDataURL(uri);
        this.qrField.el.child('img').dom.src = imgURL;

        const typeString = this.editDialog.record.constructor.getRecordName();
        this.editDialog.window.setTitle(`${typeString} ${i18n._('for')} ${account} : ${issuer}`);
    }


});

Ext.reg('mfa-htotp-secretfield', HTOTOPSecretField)

Tine.widgets.form.FieldManager.register('Tinebase', 'MFA_TOTPUserConfig', 'secret', {
    type: 'totp',
    xtype: 'mfa-htotp-secretfield',
    height: 300,
}, Tine.widgets.form.FieldManager.CATEGORY_EDITDIALOG);

Tine.widgets.form.FieldManager.register('Tinebase', 'MFA_HOTPUserConfig', 'secret', {
    type: 'hotp',
    xtype: 'mfa-htotp-secretfield',
    height: 300,
}, Tine.widgets.form.FieldManager.CATEGORY_EDITDIALOG);
