<?php
/**
 * Tine 2.0 - http://www.tine20.org
 * 
 * @package     Tinebase
 * @subpackage  Record
 * @license     http://www.gnu.org/licenses/agpl.html
 * @copyright   Copyright (c) 2007-2008 Metaways Infosystems GmbH (http://www.metaways.de)
 * @author      Matthias Greiling <m.greiling@metaways.de>
 * @version     $Id: ContainerTest.php 1014 2008-03-11 21:47:58Z nelius_weiss $
 */

/**
 * Test helper
 */
require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';

if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Tinebase_Log_Filter_FilterTest::main');
}

/**
 * Test class for Tinebase_Record_Container.
 * Generated by PHPUnit on 2008-02-14 at 12:25:04.
 */
class Tinebase_Log_Filter_FilterTest extends PHPUnit_Framework_TestCase
{
    protected $_logger = null;
    
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        $suite  = new PHPUnit_Framework_TestSuite('Tinebase_Log_Filter_FilterTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    public function setUp() {}

    /**
     * test user Filter
     */
    public function testUserFilter()
    {
        $filter = new Tinebase_Log_Filter_User('gciyi');
        $this->assertTrue($filter->accept(array('message' => 'foo accept bar')));
    }
    
    /**
     * test messsage filter
     */
    public function testMessageFilter()
    {
        $filter = new Zend_Log_Filter_Message('/accept/');
        $this->assertTrue($filter->accept(array('message' => 'foo accept bar')));
        $this->assertFalse($filter->accept(array('message' => 'foo reject bar')));
    }
    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {}
}

// Call Tinebase_Record_ContainerTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Tinebase_Log_Filter_FilterTest::main') {
    Tinebase_Log_Filter_FilterTest::main();
}
?>
