FROM osixia/openldap:1.2.5

COPY ./ci/helperimages/ldap/init.ldif /container/service/slapd/assets/config/bootstrap/ldif/bootstrap.ldif
COPY ./ci/helperimages/ldap/mozillaabalpha.schema /container/service/slapd/assets/config/bootstrap/schema/mozillaabalpha.schema
