include:
  - local: '/ci/gitlab-ci/abstract_jobs.yml'
  - local: '/ci/ci-config.yml'
  - local: '/ci/gitlab-ci/test_php_jobs.yml'
  - local: '/ci/gitlab-ci/test_js_jobs.yml'
  - local: '/ci/gitlab-ci/test_jobs.yml'
  - local: '/ci/gitlab-ci/merge_customapp.yml'
  - local: '/ci/gitlab-ci/lib.yml'

stages:
  - build
  - test
  - merge

variables:
  # also needs to be set in build job
  IMAGE_TAG: $CI_PROJECT_ID-$CI_PIPELINE_IID-$PHP_VERSION
  CI_IS_CUSTOMAPP: "true"
  # TESTS
  PHP_UNIT_ALL_TESTS_SOURCE_PARALLEL: "false"
  PHP_UNIT_ALL_TESTS_BUILT: "false"
  PHP_UNIT_SERVERTESTS: "false"
  PHP_UNIT_SETUP_TESTS: "false"
  PHP_STAN_ANALYSES: "true"
  CODE_ANALYSIS_PARALLEL_LINT: "true"
  CODE_ANALYSIS_PHPCS: "true"
  JS_E2E_TEST_SOURCE: "false"
  JS_E2E_TEST_FILTER: ""
  PHPUNIT_FILTER: ${CUSTOMAPP_DIR}_
  # TODO activate when it's working for customapps
  #      see #3835[gitlab][ci] CI customapps e2etest ausführen lassen
  JS_E2E_TESTS_SOURCE: "false"

workflow:
  rules:
    # Disable ci pipeline
    - if: $RUN_CI_PIPELINE == "false"
      when: never
    # Do not run pipelines on push for feature branches. Only merge requests should run feature branche pipelines.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /(^feat)|(^pu)|(change)/
      when: never
    - when: always

docker_build_source:
  stage: build
  trigger:
    project: tine20/tine20
    branch: $TINE20_BRANCH
    strategy: depend
  variables:
    RUN_NO_TESTS: "true"
    AUTO_MERGE: "never"
    IMAGE_TAG: $CI_PROJECT_ID-$CI_PIPELINE_IID-$PHP_VERSION
    DOCKER_BUILD_SOURCE: "true"

docker_build_built:
  stage: build
  script:
    - echo job is there for needs
  rules:
    - if: $NOT_TURE == "true"
      when: on_success
    - when: never