.abstract.merge:
  variables:
    GIT_STRATEGY: none
    MERGENONINTERACTIVE: "true" # "false" is also true! Runs not interactive if the variable exists.
    pushOptSkipCi: "true" # "false" is also true! Runs not interactive if the variable exists.
  image: dockerregistry.metaways.net/tine20/tine20/composer:2.4 #composer:2.4
  needs: []
  before_script:
    - !reference [.lib, script]
    - cp $DOCKER_GIT_CONFIG ~/.gitconfig
    - git_repo_clone
    - git config --global user.email "gitlabci@metaways.de"
    - git config --global user.name "gitlabci"
    - cd ${CI_BUILDS_DIR}
    - git clone https://gitlab.metaways.net/tine20/tine20.git merge
    - cd ${CI_BUILDS_DIR}/merge
    - git config merge.pofile.name "merge po-files driver"
    - git config merge.pofile.driver "${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/scripts/git/merge-po-files %A %O %B"
    - git config merge.pofile.recursive "binary"
    - git remote add customers https://gitlab.metaways.net/tine20/tine20.git
    # TODO remove github.com when github.com/tine20/tine20 is obsolete
    - git remote add github.com https://github.com/tine20/tine20.git
    - git remote add github https://github.com/tine-groupware/tine.git
    - cd ${CI_BUILDS_DIR}/merge/tine20
    
.abstract.merge_on_source_image:
  extends: .abstract.merge
  image: ${REGISTRY}/test-source-commit:${IMAGE_TAG}
  needs: 
    - docker_build_source

include:
  - local: '/ci/gitlab-ci/custom_merge_jobs.yml'

merge:
  stage: merge1
  extends: .abstract.merge
  script:
    - merge_merge_upwards 2021.11 2022.11
    # TODO remove main when github.com/tine20/tine20 is obsolete
    - merge_merge_upwards 2022.11 main
    - merge_merge_upwards 2022.11 2023.11
    # BE changes < 2023.11 (TODO remove that when 2022.11 is obsolete)
    - merge_merge_upwards tine20.com/2022.11-custom 2023.11
    - merge_merge_mirror origin 2023.11 github main
    - merge_merge_mirror github main origin 2023.11
    - merge_trigger_next
  rules:
    - if: $AUTO_MERGE == "never"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_REF_NAME == "2021.11" || $CI_COMMIT_REF_NAME == "2022.11" || $CI_COMMIT_REF_NAME == "2023.11" ||  $CI_COMMIT_REF_NAME == "tine20.com/2022.11-custom")
      variables:
        AUTO_MERGE_VAR: "true"
    - if: $AUTO_MERGE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /auto_merge/
    - if: $PIPELINE_TYPE =~ /auto-merge/

mergemain:
  stage: merge2
  extends: .abstract.merge
  script:
    - merge_merge_mirror origin main github.com main
    - merge_merge_mirror github.com main origin main
    - release_tag_main_if_needed
    - merge_trigger_next
  rules:
    - if: $AUTO_MERGE_MAIN == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /auto_merge_main/
    - if: $PIPELINE_TYPE =~ /auto-merge/