# todo if gitlab version >= 14.3 use gitlab "!reference [.>abstractjob<, rules]" to reduce rules copying

.php-unit-all-tests-source:
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
  stage: test
  timeout: 2h
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_MERGE_REQUEST != "false"
      changes:
        paths:
          - "**/*.php"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source/
    - if: $PIPELINE_TYPE =~ /default-tests/
    - if: $PIPELINE_TYPE =~ /mr-tests/
    - if: $CI_COMMIT_TAG
php-unit-all-tests-source-sequential:
  extends: .php-unit-all-tests-source
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  needs:
    - docker_build_source
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_TYPE != "sequential"
      when: never
    - !reference [.php-unit-all-tests-source, rules]
php-unit-all-tests-source-parallel:
  extends: .php-unit-all-tests-source
  timeout: 45m
  parallel: 5
  needs:
    - docker_build_source
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_TYPE != "parallel"
      when: never
    - !reference [.php-unit-all-tests-source, rules]
php-unit-all-tests-source-matrix:
  extends: .php-unit-all-tests-source
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
    IMAGE_TAG: ${CI_PIPELINE_ID}-${PHP_VERSION}
  needs:
    - docker_build_source
    - 'docker_build_source_matrix: [7.4]'
    - 'docker_build_source_matrix: [8.0]'
    - 'docker_build_source_matrix: [8.1]'
  parallel:
    matrix:
      - DATABASE_IMAGE:
          - "mariadb:10.6"
          - "mariadb:10.5"
          - "mariadb:10.4"
          - "mariadb:10.3"
          - "mariadb:10.2"
          - "dockerregistry.metaways.net/tine20/tine20/mysql:8"
          - "mysql:5.7"
      - PHP_VERSION:
          - "7.4"
          - "8.0"
          - "8.1"
  rules:
    - if: $PIPELINE_TYPE =~ /matrix-tests/
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_TYPE != "matrix" && $JS_E2E_TESTS_SOURCE_TYPE != "matrix"
      when: never
    - !reference [.php-unit-all-tests-source, rules]

.php-unit-all-tests-source-postfixmultiinstance:
  extends: .php-unit-all-tests-source
  variables:
    ARG_POSTFIX_INIT_SQL_PATH: /config/sql/postfixmultiinstance_tables.sql
    TINE20_EMAIL_SMTP: "active:true,backend:postfixmultiinstance,hostname:postfix,port:25,ssl:none,auth:none,name:postfix,primarydomain:mail.test,instanceName:tine.test,postfixmultiinstance_host:db,postfixmultiinstance_dbname:postfix,postfixmultiinstance_username:tine20,postfixmultiinstance_password:tine20pw"
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_MERGE_REQUEST == "true"
      changes:
        paths:
          - "**/*.php"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source-postfixmultiinstance/
    - if: $PIPELINE_TYPE =~ /default-tests/
php-unit-all-tests-source-postfixmultiinstance-sequential:
  extends: .php-unit-all-tests-source-postfixmultiinstance
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_TYPE != "sequential"
      when: never
    - !reference [.php-unit-all-tests-source-postfixmultiinstance, rules]
php-unit-all-tests-source-postfixmultiinstance-parallel:
  extends: .php-unit-all-tests-source-postfixmultiinstance
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_ALL_UNIT_TESTS_SOURCE_POSTFIXMULTIINSTANCE_TYPE != "parallel"
      when: never
    - !reference [.php-unit-all-tests-source-postfixmultiinstance, rules]


php-unit-setup-tests-source:
  extends: .php-unit-all-tests-source
  variables:
    ARG_TEST_PATH_FROM_TINE20ROOT: tests/setup/
  timeout: 90m
  allow_failure: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_SETUP_TESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_SETUP_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_SETUP_TESTS_SOURCE_MERGE_REQUEST == "true"
      changes:
        paths:
          - "**/*.php"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-setup-tests-source/
    - if: $PIPELINE_TYPE =~ /default-tests/


php-unit-servertests-source:
  extends: .php-unit-all-tests-source
  variables:
    ARG_TEST: AllServerTests
  timeout: 30m
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_SERVERTESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_SERVERTESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_SERVERTESTS_SOURCE_MERGE_REQUEST != "false"
      changes:
        paths:
          - "**/*.php"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-servertests-source/
    - if: $PIPELINE_TYPE =~ /default-tests/
    - if: $PIPELINE_TYPE =~ /mr-tests/


.php-unit-all-tests-ldap-source:
  extends: .abstract_jobs.php_unit_ldap
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
  needs:
    - docker_build_source
  timeout: 2h
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_SOURCE== "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_LDAP_SOURCE_MERGE_REQUEST != "false"
      changes:
        paths:
          - "tests/tine20/Tinebase/UserTest.php"
          - "tests/tine20/Tinebase/User/*.php"
          - "tests/tine20/Tinebase/Group/*.php"
          - "tests/tine20/Admin/Import/UserTest.php"
          - "tests/tine20/Admin/Import/GroupTest.php"
          - "tine20/Tinebase/User.php"
          - "tine20/Tinebase/User/*.php"
          - "tine20/Tinebase/User/LdapPlugin/*.php"
          - "tine20/Tinebase/Group/*.php"
          - "tine20/Tinebase/Group/LdapPlugin/*.php"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-ldap-source/
    - if: $PIPELINE_TYPE =~ /default-tests/
    - if: $PIPELINE_TYPE =~ /mr-tests/
phpunit-all-tests-ldap-source-sequential:
  extends: .php-unit-all-tests-ldap-source
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_LDAP_SOURCE_TYPE != "sequential"
      when: never
    - !reference [.php-unit-all-tests-ldap-source, rules]
php-unit-all-tests-ldap-source-parallel:
  extends: .php-unit-all-tests-ldap-source
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_UNIT_ALL_TESTS_LDAP_SOURCE_TYPE != "parallel"
      when: never
    - !reference [.php-unit-all-tests-ldap-source, rules]


.php-unit-all-tests-built:
  extends: .php-unit-all-tests-source
  variables:
    ARG_IMAGE: test-built
  needs:
    - docker_build_built
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_BUILT_MERGE_REQUEST == "true"
      changes:
        paths:
          - "**/*.php"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-built/
    - if: $PIPELINE_TYPE =~ /default-tests/
php-unit-all-tests-built-sequential:
  extends: .php-unit-all-tests-built
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_BUILT_TYPE != "sequential"
      when: never
    - !reference [.php-unit-all-tests-built, rules]
php-unit-all-tests-built-parallel:
  extends: .php-unit-all-tests-built
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_UNIT_ALL_TESTS_BUILT_TYPE != "parallel"
      when: never
    - !reference [.php-unit-all-tests-built, rules]


php-unit-tinebase-tests-built:
  extends: .php-unit-all-tests-source
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
    ARG_IMAGE: test-built
    ARG_TEST: Tinebase/AllTests
  needs:
    - docker_build_built
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_TINEBASE_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_TINEBASE_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_TINEBASE_TESTS_BUILT_MERGE_REQUEST == "true"
      changes:
        paths:
          - "**/*.php"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-tinebase-tests-built/
    - if: $PIPELINE_TYPE =~ /default-tests/


.php-unit-nogitlabci-tests-built:
  extends: .php-unit-all-tests-built
  variables:
    ARG_EXCLUDE_GROUP: ""
    ARG_GROUP: "nogitlabci"
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_MERGE_REQUEST == "true"
      changes:
        paths:
          - "**/*.php"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-nogitlabci-tests-built/
    - if: $PIPELINE_TYPE =~ /default-tests/
  allow_failure: true
php-unit-nogitlabci-tests-built-sequential:
  extends: .php-unit-nogitlabci-tests-built
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT_TYPE != "sequential"
      when: never
    - !reference [.php-unit-nogitlabci-tests-built, rules]
php-unit-nogitlabci-tests-built-parallel:
  extends: .php-unit-nogitlabci-tests-built
  timeout: 30m
  parallel: 5
  rules:
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT_TYPE != "parallel"
      when: never
    - !reference [.php-unit-nogitlabci-tests-built, rules]


php-unit-update-tests:
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
    NODE_TOTAL: 1
    NODE_INDEX: 1
  needs:
    - docker_build_source
  stage: test
  timeout: 2h
  interruptible: true
  script:
    - apk add --repository http://nl.alpinelinux.org/alpine/v3.14/main --repository http://nl.alpinelinux.org/alpine/v3.14/community php7-sodium
    - cd ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20; git fetch --unshallow; git checkout 2022.11;
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/copy_source.sh
    - cd ${TINE20ROOT}/tine20
    - su tine20 -c "php setup.php --config=/etc/tine20/config.inc.php --update -- strict=1"
    - su tine20 -c "php setup.php --config=/etc/tine20/config.inc.php --install Bookmarks,DFCom,EFile,GDPR,MatrixSynapseIntegrator,OnlyOfficeIntegrator"
    - cd ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20; git checkout 2023.11;
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/copy_source.sh
    - cd ${TINE20ROOT}/tine20
    - su tine20 -c "php setup.php --config=/etc/tine20/config.inc.php --update -- strict=1"
    - su tine20 -c "php setup.php --config=/etc/tine20/config.inc.php --install UserManual
    - cd ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20; git checkout 2024.11;
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/copy_source.sh
    - cd ${TINE20ROOT}/tine20
    - su tine20 -c "php setup.php --config=/etc/tine20/config.inc.php --update -- strict=1"
    - !reference [.abstract_jobs.php_unit, script]
  rules:
    - if: $PHP_UNIT_UPDATE_TESTS == "false"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-update-tests/
    - if: $CI_COMMIT_BRANCH != "2021.11"
      when: never
    - if: $PHP_UNIT_UPDATE_TESTS == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_UPDATE_TESTS_MERGE_REQUEST == "true"
      changes:
        paths:
          - "**/*.php"
          - "tine20/composer.*"
    - if: $PIPELINE_TYPE =~ /update-tests/