# todo if gitlab version >= 14.3 use gitlab "!reference [.>abstractjob<, rules]" to reduce rules copying

.php-unit-all-tests-source:
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
  needs:
    - docker_build_source
  stage: test
  timeout: 2h
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_MERGE_REQUEST != "false"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
php-unit-all-tests-source-sequential:
  extends: .php-unit-all-tests-source
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_MERGE_REQUEST != "false"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
php-unit-all-tests-source-parallel:
  extends: .php-unit-all-tests-source
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_MERGE_REQUEST != "false"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
php-unit-all-tests-source-matrix:
  extends: .php-unit-all-tests-source
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  parallel:
    matrix:
      - PROVIDER:
          - "mariadb:10.6"
          - "mariadb:10.5"
          - "mariadb:10.4"
          - "mariadb:10.3"
          - "mariadb:10.2"
          - "mysql:8.0"
          - "mysql:5.7"
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_TYPE != "matrix"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_MERGE_REQUEST != "false"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG


.php-unit-all-tests-source-postfixmultiinstance:
  extends: .php-unit-all-tests-source
  variables:
    ARG_POSTFIX_INIT_SQL_PATH: /config/sql/postfixmultiinstance_tables.sql
    TINE20_EMAIL_SMTP: "active:true,backend:postfixmultiinstance,hostname:postfix,port:25,ssl:none,auth:none,name:postfix,primarydomain:mail.test,instanceName:tine.test,postfixmultiinstance_host:db,postfixmultiinstance_dbname:postfix,postfixmultiinstance_username:tine20,postfixmultiinstance_password:tine20pw"
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source-postfixmultiinstance/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_SCHEDULE != "false"
php-unit-all-tests-source-postfixmultiinstance-sequential:
  extends: .php-unit-all-tests-source-postfixmultiinstance
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source-postfixmultiinstance/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_SCHEDULE != "false"
php-unit-all-tests-source-postfixmultiinstance-parallel:
  extends: .php-unit-all-tests-source-postfixmultiinstance
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_ALL_UNIT_TESTS_SOURCE_POSTFIXMULTIINSTANCE_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source-postfixmultiinstance/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_SCHEDULE != "false"


php-unit-setup-tests-source:
  extends: .php-unit-all-tests-source
  variables:
    ARG_TEST_PATH_FROM_TINE20ROOT: tests/setup/
  timeout: 90m
  allow_failure: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_SETUP_TESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_SETUP_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_SETUP_TESTS_SOURCE_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-setup-tests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_SETUP_TESTS_SOURCE_SCHEDULE != "false"


php-unit-servertests-source:
  extends: .php-unit-all-tests-source
  variables:
    ARG_TEST: AllServerTests
  timeout: 30m
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_SERVERTESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_SERVERTESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_SERVERTESTS_SOURCE_MERGE_REQUEST != "false"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-servertests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_SERVERTESTS_SOURCE_SCHEDULE != "false"


.php-unit-all-tests-ldap-source:
  extends: .abstract_jobs.php_unit_ldap
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
  needs:
    - docker_build_source
  timeout: 2h
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_SOURCE== "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_LDAP_SOURCE_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-ldap-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_LDAP_SOURCE_SCHEDULE != "false"
phpunit-all-tests-ldap-source-sequential:
  extends: .php-unit-all-tests-ldap-source
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_LDAP_SOURCE_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_SOURCE== "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_LDAP_SOURCE_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-ldap-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_LDAP_SOURCE_SCHEDULE != "false"
php-unit-all-tests-ldap-source-parallel:
  extends: .php-unit-all-tests-ldap-source
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_UNIT_ALL_TESTS_LDAP_SOURCE_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_SOURCE== "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_LDAP_SOURCE_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-ldap-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_LDAP_SOURCE_SCHEDULE != "false"


.php-unit-all-tests-built:
  extends: .php-unit-all-tests-source
  variables:
    ARG_IMAGE: test-built
  needs:
    - docker_build_built
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_BUILT_SCHEDULE == "true"
php-unit-all-tests-built-sequential:
  extends: .php-unit-all-tests-built
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_BUILT_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_BUILT_SCHEDULE == "true"
    - when: never
php-unit-all-tests-built-parallel:
  extends: .php-unit-all-tests-built
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_UNIT_ALL_TESTS_BUILT_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_BUILT_SCHEDULE == "true"


php-unit-tinebase-tests-built:
  extends: .php-unit-all-tests-source
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
    ARG_IMAGE: test-built
    ARG_TEST: Tinebase/AllTests
  needs:
    - docker_build_built
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_TINEBASE_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_TINEBASE_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_TINEBASE_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-tinebase-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_TINEBASE_TESTS_BUILT_SCHEDULE != "false"


.php-unit-nogitlabci-tests-built:
  extends: .php-unit-all-tests-built
  variables:
    ARG_EXCLUDE_GROUP: ""
    ARG_GROUP: "nogitlabci"
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-nogitlabci-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_SCHEDULE != "false"
  allow_failure: true
php-unit-nogitlabci-tests-built-sequential:
  extends: .php-unit-nogitlabci-tests-built
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-nogitlabci-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_SCHEDULE != "false"
php-unit-nogitlabci-tests-built-parallel:
  extends: .php-unit-nogitlabci-tests-built
  timeout: 30m
  parallel: 5
  rules:
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-nogitlabci-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_SCHEDULE != "false"


php-unit-update-tests:
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
    NODE_TOTAL: 1
    NODE_INDEX: 1
  needs:
    - docker_build_source
  stage: test
  timeout: 2h
  interruptible: true
  script:
    - apk add --repository http://nl.alpinelinux.org/alpine/v3.14/main --repository http://nl.alpinelinux.org/alpine/v3.14/community php7-sodium
    - cd ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20; git fetch --unshallow; git checkout 2021.11; 
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/copy_source.sh
    - cd ${TINE20ROOT}/tine20
    - su tine20 -c "php setup.php --config=/etc/tine20/config.inc.php --update -- strict=1"
    - su tine20 -c "php setup.php --config=/etc/tine20/config.inc.php --install SSO"
    - cd ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20; git checkout 2022.11; 
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/copy_source.sh
    - cd ${TINE20ROOT}/tine20
    - su tine20 -c "php setup.php --config=/etc/tine20/config.inc.php --update -- strict=1"
    - su tine20 -c "php setup.php --config=/etc/tine20/config.inc.php --install Bookmarks,DFCom,EFile,GDPR,MatrixSynapseIntegrator,OnlyOfficeIntegrator"
    - !reference [.abstract_jobs.php_unit, script]
  rules:
    - if: $PHP_UNIT_UPDATE_TESTS == "false"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-update-tests/
    - if: $CI_COMMIT_BRANCH != "2020.11"
      when: never
    - if: $PHP_UNIT_UPDATE_TESTS == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_UPDATE_TESTS_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_UPDATE_TESTS_SCHEDULE == "true"
